name: Build macOS App and Zip

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6

      - name: Install UPX
        run: |
          brew install upx

      - name: Clean previous build
        run: |
          rm -rf build dist

      - name: Build macOS app with UPX
        run: |
          pyinstaller \
            --onefile \
            --windowed \
            --name "FileComparison_1.0" \
            --upx-dir /usr/local/bin \
            "FileComparison 1.0.py"

      - name: Compress .app to zip
        run: |
          mkdir -p dist_zip
          zip -r dist_zip/FileComparison_1.0.zip dist/FileComparison_1.0.app

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileComparison_1.0-macOS
          path: dist_zip/FileComparison_1.0.zip
