name: Build macOS App and DMG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build macOS app with icon
        run: |
          pyinstaller \
            --onefile \
            --windowed \
            --name "FileComparison_1.0" \
            --icon "iconformac.icns" \
            "FileComparison 1.0.py"

      - name: Check dist folder
        run: ls -la dist

      - name: Create DMG
        run: |
          mkdir -p dist_dmg
          hdiutil create -volname "FileComparison_1.0" \
            -srcfolder "dist" \
            -ov -format UDZO "dist_dmg/FileComparison_1.0.dmg"

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: FileComparison_1.0-macOS
          path: dist_dmg/FileComparison_1.0.dmg
