name: Build macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build macOS app
        run: |
          pyinstaller --onefile --windowed --icon=myicon.icns FileComparison.py
          ls dist/

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: FileComparison-macOS
          path: dist/*
