name: Build Apps (Windows + macOS)

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Windows exe
        run: |
          pyinstaller --onefile --windowed Updated_FileComp.py --name Updated_FileComp --icon=myicon.ico

      - name: Check dist folder
        run: dir dist

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: Updated_FileComp-Windows
          path: dist/Updated_FileComp.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build macOS app
        run: |
          pyinstaller --onefile --windowed Updated_FileComp.py --name Updated_FileComp --icon=myicon.icns

      - name: Check dist folder
        run: ls -la dist

      - name: Create DMG
        run: |
          mkdir -p dist_dmg
          hdiutil create -volname "Updated_FileComp" -srcfolder "dist" -ov -format UDZO dist_dmg/Updated_FileComp.dmg

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: Updated_FileComp-macOS
          path: dist_dmg/Updated_FileComp.dmg
